---
kind: Namespace
apiVersion: v1
metadata:
  name: openshift-node-conntrack
  annotations: 
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-conntrack
  namespace: openshift-node-conntrack
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-conntrack
  namespace: openshift-node-conntrack
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: node-conntrack
  apiGroup: rbac.authorization.k8s.io

---

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: node-conntrack
  namespace: openshift-node-conntrack
spec:
  selector:
    matchLabels:
      k8s-app: node-conntrack
  template:
    metadata:
      labels:
        k8s-app: node-conntrack
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - operator: Exists
      hostNetwork: true
      containers:
      - name: track
        image: registry.svc.ci.openshift.org/clayton-test-1/node-conntrack:latest
        securityContext:
          runAsUser: 0
          privileged: true
        resources:
          requests:
            memory: 25Mi
        ports:
        - containerPort: 9179
          name: metrics
        args:
        - -listen=:9179
        - -v
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: node-conntrack
  name: node-conntrack
  namespace: openshift-node-conntrack
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - openshift-node-conntrack
  selector:
    matchLabels:
      k8s-app: node-conntrack
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    k8s-app: node-conntrack
  name: node-conntrack
  namespace: openshift-node-conntrack
spec:
  groups: []
  # - name: cluster-version
  #   rules:
  #   - alert: ClusterVersionOperatorDown
  #     annotations:
  #       message: Cluster version operator has disappeared from Prometheus target discovery. Operator may be down or disabled, cluster will not be kept up to date and upgrades will not be possible.
  #     expr: |
  #       absent(up{job="node-conntrack"} == 1)
  #     for: 10m
  #     labels:
  #       severity: critical
  # - name: cluster-operators
  #   rules:
  #   - alert: ClusterOperatorDown
  #     annotations:
  #       message: Cluster operator {{ "{{ $labels.name }}" }} has not been available for 10 mins. Operator may be down or disabled, cluster will not be kept up to date and upgrades will not be possible.
  #     expr: |
  #       cluster_operator_up{job="node-conntrack"} == 0
  #     for: 10m
  #     labels:
  #       severity: critical
  #   - alert: ClusterOperatorDegraded
  #     annotations:
  #       message: Cluster operator {{ "{{ $labels.name }}" }} has been degraded for 10 mins. Operator is degraded because {{ "{{ $labels.reason }}" }} and cluster upgrades will be unstable.
  #     expr: |
  #       cluster_operator_conditions{job="node-conntrack", condition="Degraded"} == 1
  #     for: 10m
  #     labels:
  #       severity: critical
  #   - alert: ClusterOperatorFlapping
  #     annotations:
  #       message: Cluster operator {{ "{{ $labels.name }}" }} up status is changing often. This might cause upgrades to be unstable.
  #     expr: |
  #       changes(cluster_operator_up{job="node-conntrack"}[2m]) > 2
  #     for: 10m
  #     labels:
  #       severity: warning
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # TODO this should be a clusterrole
  name: prometheus-k8s
  namespace: openshift-node-conntrack
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: openshift-node-conntrack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring

---
apiVersion: v1
kind: Service
metadata:
  name: node-conntrack
  namespace: openshift-node-conntrack
  labels:
    k8s-app: node-conntrack
spec:
  type: ClusterIP
  selector:
    k8s-app: node-conntrack
  ports:
  - port: 9179
    name: metrics
    targetPort: metrics

