kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-conntrack
  namespace: openshift-node-conntrack
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-conntrack
  namespace: openshift-node-conntrack
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: node-conntrack
  apiGroup: rbac.authorization.k8s.io
