apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: node-conntrack
  name: node-conntrack
  namespace: openshift-node-conntrack
spec:
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - openshift-node-conntrack
  selector:
    matchLabels:
      k8s-app: node-conntrack
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    k8s-app: node-conntrack
  name: node-conntrack
  namespace: openshift-node-conntrack
spec:
  groups: []
  # - name: cluster-version
  #   rules:
  #   - alert: ClusterVersionOperatorDown
  #     annotations:
  #       message: Cluster version operator has disappeared from Prometheus target discovery. Operator may be down or disabled, cluster will not be kept up to date and upgrades will not be possible.
  #     expr: |
  #       absent(up{job="node-conntrack"} == 1)
  #     for: 10m
  #     labels:
  #       severity: critical
  # - name: cluster-operators
  #   rules:
  #   - alert: ClusterOperatorDown
  #     annotations:
  #       message: Cluster operator {{ "{{ $labels.name }}" }} has not been available for 10 mins. Operator may be down or disabled, cluster will not be kept up to date and upgrades will not be possible.
  #     expr: |
  #       cluster_operator_up{job="node-conntrack"} == 0
  #     for: 10m
  #     labels:
  #       severity: critical
  #   - alert: ClusterOperatorDegraded
  #     annotations:
  #       message: Cluster operator {{ "{{ $labels.name }}" }} has been degraded for 10 mins. Operator is degraded because {{ "{{ $labels.reason }}" }} and cluster upgrades will be unstable.
  #     expr: |
  #       cluster_operator_conditions{job="node-conntrack", condition="Degraded"} == 1
  #     for: 10m
  #     labels:
  #       severity: critical
  #   - alert: ClusterOperatorFlapping
  #     annotations:
  #       message: Cluster operator {{ "{{ $labels.name }}" }} up status is changing often. This might cause upgrades to be unstable.
  #     expr: |
  #       changes(cluster_operator_up{job="node-conntrack"}[2m]) > 2
  #     for: 10m
  #     labels:
  #       severity: warning
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # TODO this should be a clusterrole
  name: prometheus-k8s
  namespace: openshift-node-conntrack
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: openshift-node-conntrack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
