apiVersion: v1
kind: Service
metadata:
  name: node-conntrack
  namespace: openshift-node-conntrack
  labels:
    k8s-app: node-conntrack
spec:
  type: ClusterIP
  selector:
    k8s-app: node-conntrack
  ports:
  - port: 9179
    name: metrics
    targetPort: metrics
